### ISSUE TITLE
Suitable for query language parsing

### ISSUE THREAD

**Issue by stephanbuys** [zkat/mona#12]
Hi, I'm a total n00b when it comes to parsers, etc. Mona is one of the first parsers that I've been able to grok quite easily. I'm particularly interested in a mechanism to take a home-grown query language and convert it to behind-the-scene queries or pipelines of queries. Happy to provide an example if Mona would be the right tool to do something like this?

**Comment by zkat** [comment]
Hey stephan! I'd say that this is definitely something you can use it for, since a similar (NLP-like) command language was one of the original reasons I even wrote mona for.

I'd take an approach something like...

``` js
function query () {
  return separatedBy(trim(clause()), string(';'))
}

function clause () {
  return sequence(function (s) {
    var subject = s(subjectClause())
    var object = s(objectClause())
    var verb = s(verbClause())
    return composeQueryCommand(subject, object, verb)
  })
}

function composeQueryCommand (subject, object, verb) {
  return subject + '<SUBJ>' + object + '<OBJ>' + verb + conjugateCupola(verb)
}

function runQuery (q) {
  return execQ(parse(query(), q))
}
```

Obviously I made up an impractical-seeming query language, but you get the point, I hope.
